### ISSUE TITLE
Actor::move_to()

### ISSUE THREAD

**Issue by antonaut** [Lundblom/C-AdventureGame#1]
What happens when an Actor moves to a new location? Will it leave the old environment? ;)

**Comment by Lundblom** [comment]
Whoops! Leftover code, all functionality has been moved to `go` c: looks something like this 

`if(current_location != nullptr)`
        `{`
            `std::clog << "Leaving current" << std::endl;`
            `    current_location->leave(this);`
        `}`
        `std::clog << "Changing current" << std::endl;`
        `current_location = e;`
        `current_location->enter(this);`

**Comment by Lundblom** [comment]
Whoops! That code is used for teleporting actors when initializing the world, so it hadn't caused any trouble yet, but it might have in the feature. Thanks c:
